name: infratest
on:
  push:
    branches:
      - master                #master에 Push 할때 발동

# https://github.com/actions/setup-java
# actions/setup-java@v2는 사용자 정의 배포를 지원하고 Zulu OpenJDK, Eclipse Temurin 및 Adopt OpenJDK를 기본적으로 지원합니다. v1은 Zulu OpenJDK만 지원합니다.
jobs:
  build: # build 라는 이름을 가진 action
    runs-on: ubuntu-latest                   # 우분투 설치
    steps:
      - name: Checkout
        uses: actions/checkout@v3            # 코드 다운로드 / 적기 귀찮은 것들을 라이브러리(스크립트 모임) 형태로 제공하는 것이 actions 이다.
      - name: Set up JDK 11
        uses: actions/setup-java@v3          # JDK를 설치
        with:
          java-version: 11
          distribution: zulu


      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew                  # gradlew 실행권한 부여


      - name: Build with Gradle
        run: ./gradlew clean build               # build 하기



      - name: Docker build
          run: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker build -t spring-boot-cicd .
            docker tag spring-boot-cicd minyeob/spring-boot-cicd:latest
            docker push minyeob/spring-boot-cicd:latest
      
      

      # UTC가 기준이기 때문에 한국시간으로 맞추려면 +9시간 해야 한다.
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Show Current Time                     #현재시간 보여주기
        run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}"



      # Beanstalk 플러그인을 사용
      # 미리 생성해둔 IAM 인증키를 사용
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: infratest
          environment_name: Infratest-env
          version_label: "infra-test-${{ steps.format-time.outputs.replaced }}"
          region: ap-northeast-2
          deployment_package: Dockerrun.aws.json